name: tox tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        django: [30, 22, 111]
        cms: [no, 37, 36, 35, 34]
        exclude:
          - django: 30
            cms: 37
          - django: 30
            cms: 36
          - django: 30
            cms: 35
          - django: 30
            cms: 34
          - python-version: 3.7
            django: 111
          - python-version: 3.6
            django: 111
          - python-version: 3.5
            django: 111
          - python-version: 2.7
            django: 30
          - python-version: 2.7
            django: 22
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Cache tox
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-tox-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-tox-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        sudo apt-get install gettext
        python -m pip install --upgrade pip setuptools tox>=1.8 coveralls codecov 'coverage<5'
    - name: Test with tox
      env:
        TOX_ENV: ${{ format('{{py{0}-django{1}-cms{2}}}', matrix.python-version, matrix.django, matrix.cms) }}
        COMMAND: coverage run
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        tox -e$TOX_ENV
        python -mcoverage xml
        coveralls
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        file: ./coverage.xml
        fail_ci_if_error: true
